relativeURLs = true
title = "Daniel Han"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Senior Research Specialist, Busara Center for Behavioral Economics"
    logo = "profile.jpg" 
    
