relativeURLs = true
title = "Daniel Han"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Economics Ph.D. Candidate, Boston University"
    logo = "profile.jpeg" 
    
